experiment:
  name: "experiment"
  version: 1.0
  seed: 31
  description: "Fintuning gemma3-4b-it on Turkish Legal Documnets"

data:
  dataset_name: "Turkish Legal Documnets"
  dataset_path: "assets"
  output_path: "outputs"
  prompt_path: "prompts/extraction_prompt.txt"
  val: {"circular": ["07.pdf", "18.pdf"],
        "decree":   ["31.pdf", "47.pdf"]}
    